import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "@/components/Theme-Provider";
import { myfontregular, myfontBold, myfontsemibold,myfontmedium } from "@/utils/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <div className={`${myfontregular.variable}  ${myfontmedium.variable} ${myfontsemibold.variable} ${myfontBold.variable} relative`}>
        <Navbar/>
        {children}
        <Footer/>
        </div>
        </ThemeProvider>
        </body>
    </html>
  );
}
